general.import = [
  "~/.config/alacritty/themes/nightfox.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14

[window]
padding.x = 12
padding.y = 0
decorations = "Buttonless"

[keyboard]
bindings = [
  { key = "F12", action = "ToggleFullScreen" }
]
