general.import = [
  "~/.config/alacritty/themes/nightfox.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 8
padding.y = 8
opacity = 0.9

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullScreen" }
]
